server:
  port: 8080

spring:
  application:
    name: calculate-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://127.0.0.1:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  profiles:
    active: local
  batch:
    job:
      # qurtz ??? ?? ????? enabled? true? ????.
      enabled: true
      names: ${job.name:NONE}
  jpa:
    hibernate:
      ddl-auto: create
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate.format_sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

logging:
  level:
    com.example.userservice.client: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, prometheus, metrics
---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:./test
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/calculate
      username: sa
      password:
      driver-class-name: org.h2.Driver
---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf8
      username: namhyeop
      password: {password}
      driver-class-name: com.mysql.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always